version: "3.8"
services:
  redis:
    image: "redis:latest"
    volumes:
      - "./redis-data:/data"
    expose:
      - 6379
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: quick-ml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --log-level debug
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GCP_SA_JSON=${GCP_SA_JSON}
      - GCS_BUCKET=${GCS_BUCKET}
    ports:
      - "8002:8002"
    volumes:
      - "./tmp_workspace:/tmp_workspace"
      - ./models:/models
    depends_on:
      - redis
